version: "3.9"

services:
  database_ignite:
    image: postgres
    container_name: db_challenge_04_tests
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
